### ISSUE TITLE
Reset cookies

### ISSUE THREAD

**Issue by farhanhu87** [reduxframework/redux-clean#2]
can we reset a cookie save button is press in redux ???
please help

**Comment by dovy** [comment]
There's a save hook example in the config. Use that to set your own cookie.

Beyond that, I have no idea what you're asking for. Please provide more context next time.

**Comment by farhanhu87** [comment]
Dear Sir,
Thanks for the reply, Sir i want to reset my cookie,created a button in redux framework option when i press  that button it should reset my cookie after pressing the button and then save the option button , please help and solve my issue here, thanks a lot  in advance
